In [93]:
import pandas as pd
import numpy as np
import time
import glob
import os
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
import os,sys
from pathlib import Path

In [94]:
dpr = pd.read_excel('dpr files/Apr.xlsx')

In [95]:
print(dpr.shape)
dpr.tail(10)

(248783, 26)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium
248773,WEST,VADODARA,VADODARA,1601.0,ALL MOTOR,YOGESH PATHAK,16A01080,70273587,MAHENDRA SONAWANE,330641,MANISHA Y PATHAK,ICM,RENEWAL,2020-2021,TW,Apr,COMPREHENSIVE,BIKES <150 CC,NaN,NaN,PREMIER,NaN,LARGE MARKET,NaN,2.0,0.025473
248774,WEST,VADODARA,VADODARA,1601.0,ALL MOTOR,YOGESH PATHAK,16A01080,70273587,MAHENDRA SONAWANE,330641,MANISHA Y PATHAK,ICM,RENEWAL,2020-2021,TW,Apr,COMPREHENSIVE,SCOOTERS,NaN,NaN,PREMIER,NaN,LARGE MARKET,NaN,3.0,0.041752
248775,WEST,VADODARA,VADODARA,1601.0,ALL MOTOR,YOGESH PATHAK,16A01080,70273587,MAHENDRA SONAWANE,330641,MANISHA Y PATHAK,ICM,RENEWAL,2021-2022,TW,Apr,COMPREHENSIVE,BIKES <125 CC,NaN,NaN,PREMIER,NaN,LARGE MARKET,NaN,1.0,0.012648
248776,WEST,VADODARA,VADODARA,1601.0,ALL MOTOR,YOGESH PATHAK,16A01080,70273587,MAHENDRA SONAWANE,330641,MANISHA Y PATHAK,ICM,RENEWAL,2021-2022,TW,Apr,COMPREHENSIVE,SCOOTERS,NaN,NaN,PREMIER,NaN,LARGE MARKET,NaN,1.0,0.013574
248777,WEST,VADODARA,VADODARA,1601.0,ALL MOTOR,YOGESH PATHAK,16A01080,70273587,MAHENDRA SONAWANE,330641,MANISHA Y PATHAK,ICM,ROLLOVER,2020-2021,TW,Apr,SA OD,BIKES <150 CC,NaN,NaN,PREMIER,NaN,LARGE MARKET,NaN,1.0,0.007203
248778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248779,Selection Status:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248780,Month: Apr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248781,_DimBusiness: 24 of 74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248782,"_metrics: Policy Count, Premium",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
dpr.drop(index = dpr.index[-5:], axis=0, inplace=True)
dpr = dpr.drop([dpr.index[0]])
print(dpr.Premium.sum())
print(dpr.shape)
dpr.head(1)

232762.34195484727
(248777, 26)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium
1,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201.0,ALL COMMERCIAL LINES,APARNA VIKESH PATEL,16A04143,70259682,REHAN SELOT,155139,SURESH DESAI & ASSOCIATES,ICM,FRESH BUSINESS,2019-2020,MARINE,Apr,OTHERS,MARINE CARGO,NaN,NaN,AGENCY CL,NaN,LARGE MARKET,NaN,1.0,0.017325

In [97]:
dpr=dpr.loc[dpr.Year=='2021-2022']
print(dpr.shape)
dpr.head(1)

(80585, 26)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium
7,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201.0,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,NaN,LARGE MARKET,NaN,1.0,0.18809

In [98]:
dpr['SM Code']=dpr['SM Code'].astype(str)
dpr.loc[dpr['SM Code'].isin(['70275076']),'SM Code']='70726848'

In [99]:
dpr['EXT_relationship']=dpr['EXT_relationship'].astype(str)

dpr.loc[dpr['EXT_relationship'].isin(['UNIMONI FINANCIAL SERVICES', 'MAS/CEEJAY/MANAPURAM/MUTHOOT','FINO PAYMENTS BANK']),\
        'EXT_relationship'] = 'OTHERS'
dpr.loc[dpr['EXT_relationship'].isin(['OTHERS']),'EXT_relationship'] = dpr['EXT_subchannel']+" - OTHERS"
dpr.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium
7,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201.0,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809

In [100]:
dpr['SM_flag'] = 'abcd'

dpr.loc[((dpr['SM Code'].str[0] == 'R')|(dpr['SM Code'].str[0] == '5')|(dpr['SM Code'].str[0] == 'K')),'SM_flag'] = 'OFFROLE'
dpr.loc[((dpr['SM Code'].str[0] == '7')),'SM_flag'] = 'ONROLE'
dpr.loc[((dpr['SM Code'].str[0] == '9')|(dpr['SM Code'].str[0] == 'D')),'SM_flag'] = 'DIRECT'

print(dpr.shape)
dpr.head(1)

(80585, 27)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag
7,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201.0,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT

In [101]:
dpr['Branch Code'] = dpr['Branch Code'].fillna(0)
dpr['Branch Code'] = dpr['Branch Code'].astype(int)
dpr['Branch Code'] = dpr['Branch Code'].astype(str)
dpr.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag
7,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT

# branchmaster

In [102]:
branchmaster_o = pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/BranchMaster.xlsx', sheet_name='Others')
print(branchmaster_o.shape)
branchmaster_o.head(1)

(2084, 2)

   Branch_Code Branch_Code_Rev
0         1001            1001

In [103]:
branchmaster_o['Branch_Code']    =branchmaster_o['Branch_Code'].astype(str)
branchmaster_o['Branch_Code_Rev']=branchmaster_o['Branch_Code_Rev'].astype(str)

branchmaster_o['Branch_Code']    =branchmaster_o['Branch_Code'].str.upper()
branchmaster_o['Branch_Code_Rev']=branchmaster_o['Branch_Code_Rev'].str.upper()

branchmaster_o = branchmaster_o.rename(columns={'Branch_Code':'Branch Code'})

In [104]:
dpr['Branch Code']=dpr['Branch Code'].astype(int)
dpr['Branch Code']=dpr['Branch Code'].astype(str)

In [105]:
dpr1 = pd.merge(dpr,branchmaster_o,on=['Branch Code'],how='left')
dpr1.shape

(80585, 28)

In [106]:
dpr1['Final_Branch_Code'] ='abcd'
dpr1.loc[dpr1['EXT_subchannel'] != 'RETAIL DIRECT','Final_Branch_Code'] = dpr1['Branch_Code_Rev']
dpr1.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Branch_Code_Rev,Final_Branch_Code
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,9201

In [107]:
branchmaster_rd = pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/BranchMaster.xlsx', sheet_name='RD')
branchmaster_rd = branchmaster_rd.rename(columns={'Branch_Code':'Branch Code'})
print(branchmaster_rd.shape)
branchmaster_rd.head(1)

(210, 2)

   Branch Code      Branch_Code_Rev
0         1803  Andhra Pradesh - RD

In [108]:
branchmaster_rd['Branch Code']=branchmaster_rd['Branch Code'].astype(str)
branchmaster_rd['Branch_Code_Rev']=branchmaster_rd['Branch_Code_Rev'].astype(str)

branchmaster_rd['Branch Code']=branchmaster_rd['Branch Code'].str.upper()
branchmaster_rd['Branch_Code_Rev']=branchmaster_rd['Branch_Code_Rev'].str.upper()

In [109]:
dpr2 = pd.merge(dpr1,branchmaster_rd,on=['Branch Code'],how='left')
print(dpr2.shape)
dpr2.head(1)

(80585, 30)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Branch_Code_Rev_x,Final_Branch_Code,Branch_Code_Rev_y
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,9201,NaN

In [110]:
dpr2.loc[dpr2['EXT_subchannel'] == 'RETAIL DIRECT','Final_Branch_Code'] = dpr2['Branch_Code_Rev_y']

dpr2 = dpr2.drop(columns=['Branch_Code_Rev_x','Branch_Code_Rev_y'])

dpr2['EXT_subchannel'] = dpr2['EXT_subchannel'].astype(str)
dpr2['EXT_subchannel'] = dpr2['EXT_subchannel'].str.upper()

dpr2.loc[dpr2['EXT_subchannel'].isin(['DIGITAL ALLIANCE','WEBSITE','WEB AGGREGATOR','TELESALES','PINK AGENCY','VIRTUAL RM']),\
        'Final_Branch_Code'] = '9202'
print(dpr2.shape)
print(dpr2.Premium.sum())
dpr2.head(1)

(80585, 28)
80641.68775613031

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201

# domainmaster

In [111]:
domainmaster = pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/Domain_ID_Master.xlsx')
print(domainmaster.shape)
domainmaster.head(1)

(3713, 2)

  DOMAIN ID    RGI ID
0  50014544  RGI45312

In [112]:
domainmaster['DOMAIN ID']=domainmaster['DOMAIN ID'].astype(str)
domainmaster['RGI ID']=domainmaster['RGI ID'].astype(str)
domainmaster=domainmaster.rename(columns={'DOMAIN ID':'SM Code'})
print(domainmaster.shape)
domainmaster.head(1)

(3713, 2)

    SM Code    RGI ID
0  50014544  RGI45312

In [113]:
dpr3 = pd.merge(dpr2,domainmaster,on=['SM Code'],how='left')
print(dpr3.shape)
dpr3.head(1)

(80585, 29)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,RGI ID
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,NaN

In [114]:
dpr3['SM_Code']=dpr3['SM Code']
dpr3.loc[((dpr3['SM_Code'].str[0]=='5')),'SM_Code']=dpr3['RGI ID']
print(dpr3.shape)
dpr3.head(1)

(80585, 30)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,RGI ID,SM_Code
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,NaN,99999998

In [115]:
dpr3 = dpr3.drop(columns=['RGI ID'])
print(dpr3.Premium.sum())
print(dpr3.shape)
dpr3.head(1)

80641.68775613031
(80585, 29)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998

# empstatus

In [116]:
empstatus = pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/Employee_DOJ-DOL.xlsx')
print(empstatus.shape)
empstatus.head(1)

(22246, 3)

      CODE        DOJ                  DOL
0  3012201 2000-10-11  2010-03-24 00:00:00

In [117]:
empstatus=empstatus.rename(columns={'CODE':'SM_Code'})
empstatus['SM_Code']=empstatus['SM_Code'].astype(str)
print(empstatus.shape)
empstatus.head(1)

(22246, 3)

   SM_Code        DOJ                  DOL
0  3012201 2000-10-11  2010-03-24 00:00:00

In [118]:
dpr3['SM_Code']=dpr3['SM_Code'].astype(str)

dpr4 = pd.merge(dpr3,empstatus,on=['SM_Code'],how='left')
print(dpr4.shape)
dpr4.head(1)

(80585, 31)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,NaN

In [119]:
dpr4['DOL_1']=dpr4['DOL']
dpr4['DOL']  =dpr4['DOL'].astype(str)

dpr4.loc[dpr4['DOL']=='Active','DOL_1']='2030-01-01 00:00:00'
dpr4.loc[dpr4['DOL']=='nan','DOL_1']   ='1900-01-01 00:00:00'
dpr4.loc[dpr4['DOL']=='NaT','DOL_1']   ='1900-01-01 00:00:00'

dpr4.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL,DOL_1
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,Apr,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,nan,1900-01-01 00:00:00

In [120]:
dpr4['DOJ']   = pd.to_datetime(dpr4['DOJ'])
dpr4['DOL_1'] = pd.to_datetime(dpr4['DOL_1'])

dpr4['Month']=dpr4['Month'].str.upper()
print(dpr4['Month'].value_counts())

dpr4 =dpr4.drop(columns=['DOL'])
print(dpr4.shape)
dpr4.head(1)

APR    80585
Name: Month, dtype: int64
(80585, 31)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01

# edit

In [121]:
dpr4['empstatus']='abcd'

dpr4.loc[((dpr4['Month'].isin(['APR']))&(dpr4['DOL_1']<"2021-04-01")),'empstatus'] ='INACTIVE'
dpr4.loc[((dpr4['Month'].isin(['APR']))&(dpr4['DOL_1']>="2021-04-01")),'empstatus']='ACTIVE'

dpr4.loc[((dpr4['Month'].isin(['MAY']))&(dpr4['DOL_1']<"2021-05-01")),'empstatus'] ='INACTIVE'
dpr4.loc[((dpr4['Month'].isin(['MAY']))&(dpr4['DOL_1']>="2021-05-01")),'empstatus']='ACTIVE'

dpr4.loc[((dpr4['Month'].isin(['JUN']))&(dpr4['DOL_1']<"2021-06-01")),'empstatus'] ='INACTIVE'
dpr4.loc[((dpr4['Month'].isin(['JUN']))&(dpr4['DOL_1']>="2021-06-01")),'empstatus']='ACTIVE'

dpr4.loc[((dpr4['Month'].isin(['JUL']))&(dpr4['DOL_1']<"2021-07-01")),'empstatus'] ='INACTIVE'
dpr4.loc[((dpr4['Month'].isin(['JUL']))&(dpr4['DOL_1']>="2021-07-01")),'empstatus']='ACTIVE'

dpr4.loc[((dpr4['Month'].isin(['AUG']))&(dpr4['DOL_1']<"2021-08-01")),'empstatus'] ='INACTIVE'
dpr4.loc[((dpr4['Month'].isin(['AUG']))&(dpr4['DOL_1']>="2021-08-01")),'empstatus']='ACTIVE'

dpr4.loc[((dpr4['Month'].isin(['SEP']))&(dpr4['DOL_1']<"2021-09-01")),'empstatus'] ='INACTIVE'
dpr4.loc[((dpr4['Month'].isin(['SEP']))&(dpr4['DOL_1']>="2021-09-01")),'empstatus']='ACTIVE'

In [122]:
dpr4.loc[((dpr4['EXT_markettype'].isin(['EMERGING MARKET']))&(dpr4['Final_Branch_Code'].isin(['SM CLUSTER 82']))),\
         'Final_Branch_Code'] = '8584'
print(dpr4.Premium.sum())
print(dpr4.shape)
dpr4.head(1)

80641.68775613031
(80585, 32)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE

# emp master

In [123]:
em = pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/Employee_Master.xlsx')
print(em.shape)
em.head(1)

(2715, 17)

,EmpCode,EmpName,Role,Grade,DOJ,Month,Status,Final Branch Code,Region,Region Final,ReportingCode,ReportingName,Reporting Role,ReportingGrade,Market,Channel,SubChannel
0,70111046,Anil Dubey,BM,IL3,2011-07-18,NaN,Active,MUMBAI - RD,MUMBAI - RD,MUMBAI,70277430,Himanshu Malik,VH-1,IL2,DM,Retail Direct,Retail Direct

In [124]:
em1=em[['EmpCode','SubChannel','Status','Role']]
em1=em1.rename(columns={'EmpCode':'SM Code'})
em1['SM Code']=em1['SM Code'].astype(str)
print(em1['Status'].value_counts())
em1.head(1)

Active      2073
Exit         485
Resigned     157
Name: Status, dtype: int64

    SM Code     SubChannel  Status Role
0  70111046  Retail Direct  Active   BM

In [125]:
dpr4['SM Code']=dpr4['SM Code'].astype(str)
dpr4_1=pd.merge(dpr4,em1,on=['SM Code'],how='left')
print(dpr4_1.shape)
dpr4_1.head(1)

(80585, 35)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,NaN,NaN,NaN

In [126]:
dpr4_1['SubChannel']=dpr4_1['SubChannel'].fillna('abcd')
dpr4_1['Status']    =dpr4_1['Status'].fillna('abcd')
dpr4_1['Role']      =dpr4_1['Role'].fillna('abcd')

dpr4_1['SubChannel']=dpr4_1['SubChannel'].str.upper()
dpr4_1['Status']    =dpr4_1['Status'].str.upper()
dpr4_1['Role']      =dpr4_1['Role'].str.upper()
dpr4_1.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD

# nosm master

In [127]:
nosmmaster = pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/NoSMMaster.xlsx')
print(nosmmaster.shape)
nosmmaster.head(1)

(3902, 9)

,SubChannel_Rev,Branch_Code_Rev,BM,CBM,RH,ZH,NM,VH_1,VH
0,BROKING & SRG,1105,70709106.0,NaN,70736153.0,70763504.0,NaN,70005171.0,70254315.0

In [128]:
nosmmaster['SubChannel_Rev']=nosmmaster['SubChannel_Rev'].str.upper()
nosmmaster=nosmmaster.rename(columns={'Branch_Code_Rev':'Final_Branch_Code'})
nosmmaster.head(1)

,SubChannel_Rev,Final_Branch_Code,BM,CBM,RH,ZH,NM,VH_1,VH
0,BROKING & SRG,1105,70709106.0,NaN,70736153.0,70763504.0,NaN,70005171.0,70254315.0

In [129]:
dpr4_1.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD

In [130]:
dpr4_1['SubChannel_Rev'] = dpr4_1['EXT_subchannel']
dpr4_1['SubChannel_Rev'] = dpr4_1['SubChannel_Rev'].str.upper()

dpr4_1.loc[((dpr4_1['EXT_markettype'].isin(['LARGE MARKET']))&(dpr4_1['EXT_subchannel'].isin(['PREMIER']))&\
         (dpr4_1['Product Category'].isin(['PC']))),'SubChannel_Rev'] = 'Premier_PC'

dpr4_1.loc[(~(dpr4_1['Product Category'].isin(['PC']))&(dpr4_1['EXT_markettype'].isin(['LARGE MARKET']))\
          &(dpr4_1['EXT_subchannel'].isin(['PREMIER']))),'SubChannel_Rev'] = 'Premier_Others'

dpr4_1.loc[((dpr4_1['EXT_markettype'].isin(['LARGE MARKET']))\
          &(dpr4_1['EXT_subchannel'].isin(['PSU BANK & CO-OPS','YBL - ASSET','PVT BANK','YBL - AFF & MUBB',\
                                        'YBL - RBG','YBL - DIRECT','HFCS & FI']))),'SubChannel_Rev'] = dpr4_1['EXT_relationship']

dpr4_1.loc[((dpr4_1['EXT_subchannel'].isin(['YES BANK']))),'SubChannel_Rev'] = 'YBL - AFF & MUBB'

dpr4_1.loc[dpr4_1['EXT_markettype'].isin(['SMART MARKET']),'SubChannel_Rev'] = 'ALL'

dpr4_1.loc[(dpr4_1['SubChannel_Rev'].isin(['PREMIER_OTHERS']))|(dpr4_1['SubChannel_Rev'].isin(['PREMIER_PC'])),\
           'EXT_subchannel']=dpr4_1['SubChannel_Rev']

dpr4_1['SubChannel_Rev'] = dpr4_1['SubChannel_Rev'].str.upper()
print(dpr4_1.Premium.sum())
print(dpr4_1.shape)
dpr4_1.head(1)

80641.68775613031
(80585, 36)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED

# sm_f

In [131]:
dpr4_1['SM_F']='abcd'
dpr4_1.loc[~(dpr4_1['EXT_markettype'].isin(['LARGE MARKET'])),'SM_F']=dpr4_1['SM Code']

dpr4_1.loc[(dpr4_1['EXT_markettype'].isin(['LARGE MARKET', 'DIRECT MARKET']))&\
           (dpr4_1['EXT_subchannel']!=dpr4_1['SubChannel']),'SM_F']='99999999'

dpr4_1.loc[(dpr4_1['EXT_markettype'].isin(['LARGE MARKET']))&(dpr4_1['EXT_subchannel'].isin(['AGENCY CL','BROKING CL']))\
           &(dpr4_1['SubChannel'].isin(['AGENCY CL','BROKING CL'])),'SM_F']=dpr4_1['SM Code']

dpr4_1.loc[(dpr4_1['EXT_markettype'].isin(['LARGE MARKET']))&(dpr4_1['EXT_subchannel'].isin(['PREMIER']))\
           &(dpr4_1['SubChannel'].isin(['PREMIER_PC','PREMIER_OTHERS'])),'SM_F']=dpr4_1['SM Code']

dpr4_1.loc[(dpr4_1['EXT_markettype'].isin(['LARGE MARKET']))&(dpr4_1['EXT_subchannel'].isin(['PREMIER']))\
           &(dpr4_1['SubChannel'].isin(['HFCS & FI','PVT BANK'])),'SM_F']=dpr4_1['SM Code']

dpr4_1.loc[(dpr4_1['SM_F'].isin(['abcd'])),'SM_F']=dpr4_1['SM Code']
dpr4_1.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999

In [132]:
dpr5 = pd.merge(dpr4_1,nosmmaster,on=(['SubChannel_Rev','Final_Branch_Code']),how='left')
print(dpr5.Premium.sum())
dpr5.head(1)

80641.68775613031

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,NaN,NaN,NaN,NaN,10003277.0,70275004.0,70254315.0

# roll up

In [133]:
ru = pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/Rollup_Master.xlsx')
print(ru.shape)
ru.head(1)

(2714, 11)

,EmpCode,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode
0,70111046,NaN,70111046.0,NaN,NaN,NaN,NaN,70277430.0,10009996,70277430,70277430

In [134]:
ru = ru.rename(columns={'EmpCode':'SM_F'})
ru['SM_F']=ru['SM_F'].astype(str)
ru.head(1)

,SM_F,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode
0,70111046,NaN,70111046.0,NaN,NaN,NaN,NaN,70277430.0,10009996,70277430,70277430

In [135]:
dpr6=pd.merge(dpr5,ru,on=['SM_F'],how='left')
print(dpr6.shape)
dpr6.head(1)

(80585, 54)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,NaN,NaN,NaN,NaN,10003277.0,70275004.0,70254315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# gwp conditions

In [136]:
dpr6['Class']='abcd'
dpr6.loc[dpr6['Group Class'].isin(['ALL MOTOR']),'Class'] = 'GWP-Motor'
dpr6.loc[(dpr6['Group Class'].isin(['ALL HEALTH'])),'Class'] = 'GWP-Health'
dpr6.loc[dpr6['Group Class'].isin(['ALL COMMERCIAL LINES']),'Class'] = 'GWP-Commercial'
dpr6.loc[(dpr6['Product Category'].isin(['HEALTH - GROUP']))|\
         (dpr6['Product SubCategory'].isin(['PA-GROUP'])),'Class'] = 'GMC+GPA'

In [137]:
dpr6['GWP-Motor']=0
dpr6['GWP-Health']=0
dpr6['GWP-Commercial']=0
dpr6['GMC+GPA']=0

dpr6.loc[dpr6['Class'].isin(['GWP-Motor']),'GWP-Motor'] = dpr6['Premium']
dpr6.loc[dpr6['Class'].isin(['GWP-Health']),'GWP-Health'] = dpr6['Premium']
dpr6.loc[dpr6['Class'].isin(['GWP-Commercial']),'GWP-Commercial'] = dpr6['Premium']
dpr6.loc[dpr6['Class'].isin(['GMC+GPA']),'GMC+GPA'] = dpr6['Premium']

print(dpr6['Premium'].sum())
print((dpr6['GWP-Motor']+dpr6['GWP-Health']+dpr6['GWP-Commercial']+dpr6['GMC+GPA']).sum())

80641.68775613031
77889.47114713032

In [138]:
dpr6['LT_Flag']='No'
dpr6.loc[dpr6['System'].isin(['MANUAL_ADV_REV1_LTP','MANUAL_ADV_REV1_LTP_ADD']),'LT_Flag']='Yes'
dpr6.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,NaN,NaN,NaN,NaN,10003277.0,70275004.0,70254315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GWP-Health,0.0,0.18809,0.0,0.0,No

In [139]:
dpr6['BM_F']='abcd'
dpr6['CBM_F']='abcd'
dpr6['RH_F']='abcd'
dpr6['ZH_F']='abcd'
dpr6['NM_F']='abcd'
dpr6['VH_1_F']='abcd'
dpr6['VH_F']='abcd'
dpr6.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,NaN,NaN,NaN,NaN,10003277.0,70275004.0,70254315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,abcd,abcd,abcd

In [140]:
dpr6.loc[dpr6['EXT_markettype'].isin(['EMERGING MARKET','SMART MARKET']),'BM_F']=dpr6['BM']
dpr6.loc[dpr6['EXT_markettype'].isin(['EMERGING MARKET','SMART MARKET']),'CBM_F']=dpr6['CBM']
dpr6.loc[dpr6['EXT_markettype'].isin(['EMERGING MARKET','SMART MARKET']),'RH_F']=dpr6['RH']
dpr6.loc[dpr6['EXT_markettype'].isin(['EMERGING MARKET','SMART MARKET']),'ZH_F']=dpr6['ZH']
dpr6.loc[dpr6['EXT_markettype'].isin(['EMERGING MARKET','SMART MARKET']),'NM_F']=dpr6['NM']
dpr6.loc[dpr6['EXT_markettype'].isin(['EMERGING MARKET','SMART MARKET']),'VH_1_F']=dpr6['VH_1']
dpr6.loc[dpr6['EXT_markettype'].isin(['EMERGING MARKET','SMART MARKET']),'VH_F']=dpr6['VH']
dpr6.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,NaN,NaN,NaN,NaN,10003277.0,70275004.0,70254315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,abcd,abcd,abcd

In [141]:
dpr6.loc[dpr6['SM_flag'].isin(['ONROLE'])&dpr6['EXT_markettype'].isin(['LARGE MARKET']),'BM_F']=dpr6['BM_R']
dpr6.loc[dpr6['SM_flag'].isin(['ONROLE'])&dpr6['EXT_markettype'].isin(['LARGE MARKET']),'CBM_F']=dpr6['CBM_R']
dpr6.loc[dpr6['SM_flag'].isin(['ONROLE'])&dpr6['EXT_markettype'].isin(['LARGE MARKET']),'RH_F']=dpr6['RH_R']
dpr6.loc[dpr6['SM_flag'].isin(['ONROLE'])&dpr6['EXT_markettype'].isin(['LARGE MARKET']),'ZH_F']=dpr6['ZH_R']
dpr6.loc[dpr6['SM_flag'].isin(['ONROLE'])&dpr6['EXT_markettype'].isin(['LARGE MARKET']),'NM_F']=dpr6['NM']
dpr6.loc[dpr6['SM_flag'].isin(['ONROLE'])&dpr6['EXT_markettype'].isin(['LARGE MARKET']),'VH_1_F']=dpr6['VH_1']
dpr6.loc[dpr6['SM_flag'].isin(['ONROLE'])&dpr6['EXT_markettype'].isin(['LARGE MARKET']),'VH_F']=dpr6['VH']
dpr6.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,NaN,NaN,HEALTH AGENCY - TIED,nan,LARGE MARKET,NaN,1.0,0.18809,DIRECT,9201,99999998,NaT,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,NaN,NaN,NaN,NaN,10003277.0,70275004.0,70254315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,abcd,abcd,abcd

In [142]:
dpr6=dpr6.fillna('abcd')

In [143]:
dpr6.loc[dpr6['BM_F'].isin(['abcd']),'BM_F']=dpr6['BM']
dpr6.loc[dpr6['CBM_F'].isin(['abcd']),'CBM_F']=dpr6['CBM']
dpr6.loc[dpr6['RH_F'].isin(['abcd']),'RH_F']=dpr6['RH']
dpr6.loc[dpr6['ZH_F'].isin(['abcd']),'ZH_F']=dpr6['ZH']
dpr6.loc[dpr6['NM_F'].isin(['abcd']),'NM_F']=dpr6['NM']
dpr6.loc[dpr6['VH_1_F'].isin(['abcd']),'VH_1_F']=dpr6['VH_1']
dpr6.loc[dpr6['VH_F'].isin(['abcd']),'VH_F']=dpr6['VH']
print(dpr6.Premium.sum())
print(dpr6.shape)
dpr6.head(1)

80641.68775613031
(80585, 67)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0

# RM [bda]

In [144]:
rm_bda=pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/Relationship_Master.xlsx',sheet_name='Bancassurance and Digital Allia')
print(rm_bda.shape)
rm_bda.head(1)

(809, 9)

,Agent Code,xyz,Agent Name,IMD Code,IMD Name,AGNT&IMD,Countif,Digital Alliance,Relationship
0,16B31217,B31,BANK OF INDIA,986772,BOI LTD,16B31217986772,1,NaN,BOI

In [145]:
rm_bda=rm_bda[['Agent Code','IMD Code','Relationship']]
rm_bda=rm_bda.rename(columns={'Relationship':'Relationship_bda'})
rm_bda.head(1)

  Agent Code IMD Code Relationship_bda
0   16B31217   986772              BOI

In [146]:
rm_bda['Agent Code']=rm_bda['Agent Code'].astype(str)
rm_bda['Agent Code']=rm_bda['Agent Code'].str.upper()

rm_bda['IMD Code']=rm_bda['IMD Code'].astype(str)
rm_bda['IMD Code']=rm_bda['IMD Code'].str.upper()

dpr6['Agent Code']=dpr6['Agent Code'].astype(str)
dpr6['Agent Code']=dpr6['Agent Code'].str.upper()

dpr6['IMD Code']=dpr6['IMD Code'].astype(str)
dpr6['IMD Code']=dpr6['IMD Code'].str.upper()

print(dpr6.shape)
dpr6.head(1)

(80585, 67)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0

In [147]:
dpr7=pd.merge(dpr6,rm_bda,on=['Agent Code','IMD Code'],how='left')
print(dpr7.shape)
print(dpr7.Premium.sum())
dpr7.head(1)

(80585, 68)
80641.68775613031

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Relationship_bda
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN

# RM [ab]

In [148]:
rm_ab=pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/Relationship_Master.xlsx',sheet_name='Agency & Broking')
print(rm_ab.shape)
rm_ab.head(1)

(944, 7)

,Agent Code,Unnamed: 1,Name,Merge Code,Business,Merged Name,x
0,14A12527,A12,ANJANADEVI G GANJIHAL / KUPPU SWAMY KISHORE KUMAR,Merge code - Agent 11,1.297907,KUPPU SWAMY KISHORE KUMAR,MURTHY P

In [149]:
rm_ab=rm_ab[['Agent Code','Merge Code','Merged Name']]
rm_ab=rm_ab.rename(columns={'Merge Code':'Relationship_ab'})
rm_ab['Agent Code']=rm_ab['Agent Code'].astype(str)
rm_ab['Agent Code']=rm_ab['Agent Code'].str.upper()
print(rm_ab.shape)
rm_ab.head(1)

(944, 3)

  Agent Code        Relationship_ab                Merged Name
0   14A12527  Merge code - Agent 11  KUPPU SWAMY KISHORE KUMAR

In [150]:
dpr8=pd.merge(dpr7,rm_ab,on=['Agent Code'],how='left')
print(dpr8.shape)
dpr8.head(1)

(80585, 70)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Relationship_bda,Relationship_ab,Merged Name
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN,NaN,NaN

# RM [oem]

In [151]:
rm_oem=pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/Relationship_Master.xlsx',sheet_name='OEM or motor')
print(rm_oem.shape)
rm_oem.head(1)

(1426, 3)

      IMD  Relationship  x
0  986620  Deep Hyundai  1

In [152]:
rm_oem=rm_oem[['IMD','Relationship']]
rm_oem['IMD']=rm_oem['IMD'].astype(str)
rm_oem['IMD']=rm_oem['IMD'].str.upper()
rm_oem=rm_oem.rename(columns={'IMD':'IMD Code','Relationship':'Relationship_oem'})
rm_oem.head(1)

  IMD Code Relationship_oem
0   986620     Deep Hyundai

In [153]:
dpr9=pd.merge(dpr8,rm_oem,on=['IMD Code'],how='left')

print(dpr9.shape)
dpr9.head(1)

(80585, 71)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Relationship_bda,Relationship_ab,Merged Name,Relationship_oem
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN,NaN,NaN,NaN

In [154]:
dpr9['Relationship_Final_code']='abcd'
dpr9['Relationship_Final_name']='abcd'

#BANCA AND DIGITAL ALLIANCE
dpr9.loc[dpr9['EXT_subchannel'].isin(['PSU BANK & CO-OPS','YBL - ASSET','PVT BANK','DIGITAL ALLIANCE',\
                                      'YBL - AFF & MUBB','YBL - RBG','YBL - DIRECT','HFCS & FI']),\
         'Relationship_Final_code'] = dpr9['SubChannel_Rev']

dpr9.loc[dpr9['EXT_subchannel'].isin(['PSU BANK & CO-OPS','YBL - ASSET','PVT BANK','DIGITAL ALLIANCE',\
                                      'YBL - AFF & MUBB','YBL - RBG','YBL - DIRECT','HFCS & FI']),\
         'Relationship_Final_name'] = dpr9['Relationship_bda']

dpr9.loc[dpr9['EXT_subchannel'].isin(['YBL - ASSET','YBL - AFF & MUBB','YBL - RBG','YBL - DIRECT']),\
         'Relationship_Final_name'] = 'Yes Bank'

dpr9['Relationship_Final_code']=dpr9['Relationship_Final_code'].fillna('abcd')
dpr9['Relationship_Final_name']=dpr9['Relationship_Final_name'].fillna('abcd')

dpr9.loc[(dpr9['EXT_subchannel'].isin(['PSU BANK & CO-OPS','YBL - ASSET','PVT BANK','DIGITAL ALLIANCE',\
                                      'YBL - AFF & MUBB','YBL - RBG','YBL - DIRECT','HFCS & FI']))&\
         (dpr9['Relationship_Final_name'].isin(['abcd'])),'Relationship_Final_name'] = dpr9['EXT_subchannel']+" - Others"

dpr9.loc[(dpr9['EXT_subchannel'].isin(['PSU BANK & CO-OPS','YBL - ASSET','PVT BANK','DIGITAL ALLIANCE',\
                                      'YBL - AFF & MUBB','YBL - RBG','YBL - DIRECT','HFCS & FI']))&\
         (dpr9['Relationship_Final_name'].isin(['abcd'])),'Relationship_Final_code'] = dpr9['SubChannel_Rev']



#AGENCY AND BROKING
dpr9.loc[dpr9['EXT_subchannel'].isin(['AGENCY CL','BROKING & SRG','BROKING CL','HEALTH AGENCY - TIED',\
                                        'HEALTH AGENCY - VARIABLE','PINK AGENCY','PREMIER','SIGNATURE','TRAVEL','VIRTUAL RM',\
                                        'WEB AGGREGATOR']),'Relationship_Final_name'] = dpr9['Merged Name']

dpr9.loc[dpr9['EXT_subchannel'].isin(['AGENCY CL','BROKING & SRG','BROKING CL','HEALTH AGENCY - TIED',\
                                        'HEALTH AGENCY - VARIABLE','PINK AGENCY','PREMIER','SIGNATURE','TRAVEL','VIRTUAL RM',\
                                        'WEB AGGREGATOR']),'Relationship_Final_code'] = dpr9['Relationship_ab']

dpr9['Relationship_Final_code']=dpr9['Relationship_Final_code'].fillna('abcd')
dpr9['Relationship_Final_name']=dpr9['Relationship_Final_name'].fillna('abcd')

dpr9.loc[(dpr9['EXT_subchannel'].isin(['AGENCY CL','BROKING & SRG','BROKING CL','HEALTH AGENCY - TIED',\
                                        'HEALTH AGENCY - VARIABLE','PINK AGENCY','PREMIER','SIGNATURE','TRAVEL','VIRTUAL RM',\
                                        'WEB AGGREGATOR']))&\
         (dpr9['Relationship_Final_name'].isin(['abcd'])),'Relationship_Final_name'] = dpr9['Agent Name']

dpr9.loc[(dpr9['EXT_subchannel'].isin(['AGENCY CL','BROKING & SRG','BROKING CL','HEALTH AGENCY - TIED',\
                                        'HEALTH AGENCY - VARIABLE','PINK AGENCY','PREMIER','SIGNATURE','TRAVEL','VIRTUAL RM',\
                                        'WEB AGGREGATOR']))&\
         (dpr9['Relationship_Final_code'].isin(['abcd'])),'Relationship_Final_code'] = dpr9['Agent Code']

dpr9.loc[(dpr9['EXT_subchannel'].isin(['AGENCY CL','BROKING & SRG','BROKING CL','HEALTH AGENCY - TIED',\
                                        'HEALTH AGENCY - VARIABLE','PINK AGENCY','PREMIER','SIGNATURE','TRAVEL','VIRTUAL RM',\
                                        'WEB AGGREGATOR']))&\
         (dpr9['Relationship_Final_name'].isin(['DIRECT'])),'Relationship_Final_name'] = dpr9['IMD Name']

dpr9.loc[(dpr9['EXT_subchannel'].isin(['AGENCY CL','BROKING & SRG','BROKING CL','HEALTH AGENCY - TIED',\
                                        'HEALTH AGENCY - VARIABLE','PINK AGENCY','PREMIER','SIGNATURE','TRAVEL','VIRTUAL RM',\
                                        'WEB AGGREGATOR']))&\
         (dpr9['Relationship_Final_code'].isin(['DIRECT'])),'Relationship_Final_code'] = dpr9['IMD Code']


#MOTOR OR OEM
dpr9.loc[dpr9['EXT_subchannel'].isin(['OEM TW','OEM CV','OEM PC']),'Relationship_Final_name'] = dpr9['Relationship_oem']
dpr9.loc[dpr9['EXT_subchannel'].isin(['OEM TW','OEM CV','OEM PC']),'Relationship_Final_code'] = dpr9['IMD Code']

dpr9['Relationship_Final_name']=dpr9['Relationship_Final_name'].fillna('abcd')

dpr9.loc[(dpr9['EXT_subchannel'].isin(['OEM TW','OEM CV','OEM PC']))&\
         (dpr9['Relationship_Final_name'].isin(['abcd'])),'Relationship_Final_name'] = dpr9['IMD Name']

#Direct Channels

dpr9['Relationship_Final_code']=dpr9['Relationship_Final_code'].fillna('abcd')
dpr9['Relationship_Final_name']=dpr9['Relationship_Final_name'].fillna('abcd')

dpr9.loc[(dpr9['EXT_subchannel'].isin(['RETAIL DIRECT','TELESALES','WEBSITE', 'VIRTUAL RM', 'PINK AGENCY']))&\
          (dpr9['Relationship_Final_name'].isin(['abcd'])),'Relationship_Final_name'] = dpr9['EXT_subchannel']

dpr9.loc[(dpr9['EXT_subchannel'].isin(['RETAIL DIRECT','TELESALES','WEBSITE','VIRTUAL RM', 'PINK AGENCY']))&\
          (dpr9['Relationship_Final_code'].isin(['abcd'])),'Relationship_Final_code'] = dpr9['EXT_subchannel']

dpr9=dpr9.drop(columns=['Relationship_bda','Relationship_ab','Relationship_oem'])
dpr9.head(1)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Merged Name,Relationship_Final_code,Relationship_Final_name
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN,12A20064,G SUGANYA

In [155]:
dpr9['Relationship_Final_name']=dpr9['Relationship_Final_name'].replace(r'^\s*$', np.nan, regex=True)
dpr9['Relationship_Final_name']=dpr9['Relationship_Final_name'].fillna('abcd')
dpr9['Relationship_Final_code']=dpr9['Relationship_Final_code'].replace(r'^\s*$', np.nan, regex=True)
dpr9['Relationship_Final_code']=dpr9['Relationship_Final_code'].fillna('abcd')

In [156]:
dpr9['Final_Code'] = 'abcd'

dpr9.loc[~(dpr9['SM_F'].isin(['abcd','99999999','11111111','55555555']))&(dpr9['Status']=='ACTIVE'),'Final_Code'] = dpr9['SM_F']
dpr9.loc[(dpr9['Final_Code']=='abcd')&(dpr9['SSM_R']!='abcd'), 'Final_Code']=dpr9['SSM_R']
dpr9.loc[(dpr9['Final_Code']=='abcd')&(dpr9['BM_F']!='abcd'),  'Final_Code']=dpr9['BM_F']
dpr9.loc[(dpr9['Final_Code']=='abcd')&(dpr9['CBM_F']!='abcd'), 'Final_Code']=dpr9['CBM_F']
dpr9.loc[(dpr9['Final_Code']=='abcd')&(dpr9['RH_F']!='abcd'),  'Final_Code']=dpr9['RH_F']
dpr9.loc[(dpr9['Final_Code']=='abcd')&(dpr9['ZH_F']!='abcd'),  'Final_Code']=dpr9['ZH_F']
dpr9.loc[(dpr9['Final_Code']=='abcd')&(dpr9['NM_F']!='abcd'),  'Final_Code']=dpr9['NM_F']
dpr9.loc[(dpr9['Final_Code']=='abcd')&(dpr9['VH_1_F']!='abcd'),'Final_Code']=dpr9['VH_1_F']
dpr9.loc[(dpr9['Final_Code']=='abcd')&(dpr9['VH_F']!='abcd'),  'Final_Code']=dpr9['VH_F']

print(dpr9.shape)
dpr9.head(1)

(80585, 71)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Merged Name,Relationship_Final_code,Relationship_Final_name,Final_Code
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN,12A20064,G SUGANYA,10003277.0

In [157]:
dpr9.loc[dpr9['Final_Code'].isin(['abcd']),'Final_Code']='99999999'
dpr9['Final_Code']=dpr9['Final_Code'].astype(float)
dpr9['Final_Code']=dpr9['Final_Code'].astype(int)
dpr9['Final_Code']=dpr9['Final_Code'].astype(str)

print(dpr9.shape)
print(dpr9.Premium.sum())
dpr9.head(1)

(80585, 71)
80641.68775613031

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Merged Name,Relationship_Final_code,Relationship_Final_name,Final_Code
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN,12A20064,G SUGANYA,10003277

# Codes

In [158]:
fc = dpr9[['Final_Code','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
fc = fc.rename(columns={'Final_Code':'Code'})
fc['Code']=fc['Code'].astype(str)
fc['Source']='final'
fc['Source_num']='11'

sm_f = dpr9[['SM_F','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
sm_f = sm_f.rename(columns={'SM_F':'Code'})
sm_f['Code']=sm_f['Code'].astype(str)
sm_f['Source']='SM_F'
sm_f['Source_num']='10'

sm = dpr9[['SM Code','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
sm = sm.rename(columns={'SM Code':'Code'})
sm['Code']=sm['Code'].astype(str)
sm['Source']='sm'
sm['Source_num']='9'

SSM = dpr9[['SSM_R','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
SSM = SSM.rename(columns={'SSM_R':'Code'})
SSM['Code']=SSM['Code'].astype(str)
SSM['Source']='SSM'
SSM['Source_num']='8'

BM_F = dpr9[['BM_F','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
BM_F = BM_F.rename(columns={'BM_F':'Code'})
BM_F['Code']=BM_F['Code'].astype(str)
BM_F['Source']='BM'
BM_F['Source_num']='7'

CBM_F = dpr9[['CBM_F','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
CBM_F = CBM_F.rename(columns={'CBM_F':'Code'})
CBM_F['Code']=CBM_F['Code'].astype(str)
CBM_F['Source']='CBM'
CBM_F['Source_num']='6'

RH_F = dpr9[['RH_F','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
RH_F = RH_F.rename(columns={'RH_F':'Code'})
RH_F['Code']=RH_F['Code'].astype(str)
RH_F['Source']='RH'
RH_F['Source_num']='5'

ZH_F = dpr9[['ZH_F','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
ZH_F = ZH_F.rename(columns={'ZH_F':'Code'})
ZH_F['Code']=ZH_F['Code'].astype(str)
ZH_F['Source']='ZH'
ZH_F['Source_num']='4'

NM_F = dpr9[['NM_F','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
NM_F = NM_F.rename(columns={'NM_F':'Code'})
NM_F['Code']=NM_F['Code'].astype(str)
NM_F['Source']='NM'
NM_F['Source_num']='3'

VH_1_F = dpr9[['VH_1_F','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
VH_1_F = VH_1_F.rename(columns={'VH_1_F':'Code'})
VH_1_F['Code']=VH_1_F['Code'].astype(str)
VH_1_F['Source']='VH_1'
VH_1_F['Source_num']='2'

VH_F = dpr9[['VH_F','Month','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
VH_F = VH_F.rename(columns={'VH_F':'Code'})
VH_F['Code']=VH_F['Code'].astype(str)
VH_F['Source']='VH'
VH_F['Source_num']='1'

In [159]:
sm=sm.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
sm=sm.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

sm_f=sm_f.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
sm_f=sm_f.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

SSM=SSM.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
SSM=SSM.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

BM_F=BM_F.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
BM_F=BM_F.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

CBM_F=CBM_F.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
CBM_F=CBM_F.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

RH_F=RH_F.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
RH_F=RH_F.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

ZH_F=ZH_F.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
ZH_F=ZH_F.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

NM_F=NM_F.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
NM_F=NM_F.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

VH_1_F=VH_1_F.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
VH_1_F=VH_1_F.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

VH_F=VH_F.groupby(['Code','Source','Source_num','Month','LT_Flag']).sum()
VH_F=VH_F.reset_index(level=['Code','Source','Source_num','Month','LT_Flag'])

In [160]:
df=fc.append([sm,sm_f,SSM,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F])
print(df.shape)
df.head(1)

(88056, 10)

,Code,Month,LT_Flag,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,Premium,Source,Source_num
0,10003277,APR,No,0.0,0.18809,0.0,0.0,0.18809,final,11

In [161]:
df['Source']=df['Source'].astype(str)
df['Source']=df['Source'].str.upper()
df.loc[((df['Source'].isin(['SM_F','SM','SSM','BM','CBM','RH','ZH']))&(df['LT_Flag'].isin(['Yes']))),'Premium']=0
df.loc[((df['Source'].isin(['SM_F','SM','SSM','BM','CBM','RH','ZH']))&(df['LT_Flag'].isin(['Yes']))),'GWP-Motor']=0

# emp master for role

In [162]:
em = pd.read_excel('C:/Users/70775633/Desktop/Masters_for_all/Employee_Master.xlsx')
print(em.shape)
em.head(1)

(2715, 17)

,EmpCode,EmpName,Role,Grade,DOJ,Month,Status,Final Branch Code,Region,Region Final,ReportingCode,ReportingName,Reporting Role,ReportingGrade,Market,Channel,SubChannel
0,70111046,Anil Dubey,BM,IL3,2011-07-18,NaN,Active,MUMBAI - RD,MUMBAI - RD,MUMBAI,70277430,Himanshu Malik,VH-1,IL2,DM,Retail Direct,Retail Direct

In [163]:
em_r=em[['EmpCode','EmpName','Role','DOJ','Month','ReportingCode','ReportingName','Reporting Role']]

em_r['Month']=em_r['Month'].astype(str)
em_r['Month']=em_r['Month'].fillna('abcd')
em_r.loc[em_r['Month'].isin(['nan']),'Month']='abcd'

em_r['EmpCode']=em_r['EmpCode'].astype(str)
em_r['EmpName']=em_r['EmpName'].astype(str)
em_r['Role']=em_r['Role'].astype(str)
em_r['ReportingCode']=em_r['ReportingCode'].astype(str)
em_r['ReportingName']=em_r['ReportingName'].astype(str)
em_r['Reporting Role']=em_r['Reporting Role'].astype(str)
print(em_r.shape)
em_r.head(1)

(2715, 8)

<ipython-input-163-5aba894c518e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  em_r['Month']=em_r['Month'].astype(str)
<ipython-input-163-5aba894c518e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  em_r['Month']=em_r['Month'].fillna('abcd')
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
<ipython-input-163-5aba894c518e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  em_r['EmpCode']=em_r['EmpCode'].astype(str)
<ipython-input-163-5aba894c518e>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  em_r['EmpName']=em_r['EmpName'].astype(str)
<ipython-input-163-5aba894c518e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  em_r['Role']=em_r['Role'].astype(str)
<ipython-input-163-5aba894c518e>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  em_r['ReportingCode']=em_r['ReportingCode'].astype(str)
<ipython-input-163-5aba894c518e>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  em_r['ReportingName']=em_r['ReportingName'].astype(str)
<ipython-input-163-5aba894c518e>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  em_r['Reporting Role']=em_r['Reporting Role'].astype(str)

,EmpCode,EmpName,Role,DOJ,Month,ReportingCode,ReportingName,Reporting Role
0,70111046,Anil Dubey,BM,2011-07-18,abcd,70277430,Himanshu Malik,VH-1

In [164]:
print(em_r.shape)
em_r=em_r.groupby(['EmpCode','EmpName','Role','DOJ','Month','ReportingCode','ReportingName','Reporting Role']).sum()
em_r=em_r.reset_index(level=['EmpCode','EmpName','Role','DOJ','Month','ReportingCode','ReportingName','Reporting Role'])
print(em_r.shape)
em_r.head(1)

(2715, 8)
(2715, 8)

,EmpCode,EmpName,Role,DOJ,Month,ReportingCode,ReportingName,Reporting Role
0,10001208,Godfrey D'Souza,Business Support,2003-07-01,abcd,70288219,Sameer Bhagwat,Business Support

In [165]:
df['Code']=df['Code'].astype(str)
df.loc[df['Code'].isin(['abcd']),'Code']='99999999'
df.loc[((df['Code'].str[0] == 'R')|(df['Code'].str[0] == 'K')),'Code'] = '11111111'
df.loc[(df['Code'].str[0] == 'D'),'Code'] = '55555555'
df['Code']=df['Code'].astype(float)
df['Code']=df['Code'].astype(int)
df['Code']=df['Code'].astype(str)
print(df.shape)
df.head(1)

(88056, 10)

,Code,Month,LT_Flag,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,Premium,Source,Source_num
0,10003277,APR,No,0.0,0.18809,0.0,0.0,0.18809,FINAL,11

In [166]:
df1=pd.merge(df,em_r, how='left', on=None, left_on='Code', right_on='EmpCode',left_index=False, right_index=False, sort=True)
print(df1.shape)
df1.head(1)

(88056, 18)

,Code,Month_x,LT_Flag,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,Premium,Source,Source_num,EmpCode,EmpName,Role,DOJ,Month_y,ReportingCode,ReportingName,Reporting Role
0,10003277,APR,No,0.0,0.18809,0.0,0.0,0.18809,FINAL,11,10003277,Puneet Bhatia,NM,2004-05-06,abcd,70275004,Nps Shekhawat,VH-1

In [167]:
df1=df1.rename(columns={'Month_y':'Month_emp','Month_x':'Month'})
df1['Month_emp']=df1['Month_emp'].str.upper()
df1['Month']=df1['Month'].str.upper()
df1.head(1)

,Code,Month,LT_Flag,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,Premium,Source,Source_num,EmpCode,EmpName,Role,DOJ,Month_emp,ReportingCode,ReportingName,Reporting Role
0,10003277,APR,No,0.0,0.18809,0.0,0.0,0.18809,FINAL,11,10003277,Puneet Bhatia,NM,2004-05-06,ABCD,70275004,Nps Shekhawat,VH-1

In [168]:
d = {'JAN':1, 'FEB':2, 'MAR':3, 'APR':4, 'MAY':5, 'JUN':6, 'JUL':7, 'AUG':8, 'SEP':9, 'OCT':10, 'NOV':11, 'DEC':12}

In [169]:
df1['Month_num']=df1['Month']
df1['Month_emp_num']=df1['Month_emp']

df1.Month_num = df1.Month_num.map(d)
df1.Month_emp_num = df1.Month_emp_num.map(d)

df1.head(1)

,Code,Month,LT_Flag,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,Premium,Source,Source_num,EmpCode,EmpName,Role,DOJ,Month_emp,ReportingCode,ReportingName,Reporting Role,Month_num,Month_emp_num
0,10003277,APR,No,0.0,0.18809,0.0,0.0,0.18809,FINAL,11,10003277,Puneet Bhatia,NM,2004-05-06,ABCD,70275004,Nps Shekhawat,VH-1,4,NaN

In [170]:
df1['Month_emp_num']=df1['Month_emp_num'].fillna(0)
df1['Month_emp_num']=df1['Month_emp_num'].astype(int)
df1['Month_num']=df1['Month_num'].astype(int)
df1.head(1)

,Code,Month,LT_Flag,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,Premium,Source,Source_num,EmpCode,EmpName,Role,DOJ,Month_emp,ReportingCode,ReportingName,Reporting Role,Month_num,Month_emp_num
0,10003277,APR,No,0.0,0.18809,0.0,0.0,0.18809,FINAL,11,10003277,Puneet Bhatia,NM,2004-05-06,ABCD,70275004,Nps Shekhawat,VH-1,4,0

In [171]:
df1['Source']=df1['Source'].astype(str)
df1.loc[(df1['Source'].isin(['final']))&(df1['Month_emp_num']>df1['Month_num']),'Code']=df1['ReportingCode']
df1.loc[(df1['Source'].isin(['final']))&(df1['Month_emp_num']>df1['Month_num']),'EmpName']=df1['ReportingName']
df1.loc[(df1['Source'].isin(['final']))&(df1['Month_emp_num']>df1['Month_num']),'Role']=df1['Reporting Role']

In [172]:
df1=df1[['Code','EmpName','Role','Source','Source_num','Month','DOJ','LT_Flag','GWP-Motor','GWP-Health','GWP-Commercial','GMC+GPA','Premium']]
df1.head(1)

,Code,EmpName,Role,Source,Source_num,Month,DOJ,LT_Flag,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,Premium
0,10003277,Puneet Bhatia,NM,FINAL,11,APR,2004-05-06,No,0.0,0.18809,0.0,0.0,0.18809

# ranking

In [173]:
print(dpr9.shape)
dpr9.head(1)

(80585, 71)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Merged Name,Relationship_Final_code,Relationship_Final_name,Final_Code
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN,12A20064,G SUGANYA,10003277

In [174]:
dpr_a=dpr9[['Relationship_Final_name','Month','Premium']]
dpr_a.head(1)

  Relationship_Final_name Month  Premium
0               G SUGANYA   APR  0.18809

In [175]:
dpr_a['Relationship_Final_name']=dpr_a['Relationship_Final_name'].astype(str)
dpr_a['Relationship_Final_name']=dpr_a['Relationship_Final_name'].str.upper()
dpr_a['Month']=dpr_a['Month'].astype(str)
dpr_a['Premium']=dpr_a['Premium'].astype(float)

<ipython-input-175-ec85dbbd700c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dpr_a['Relationship_Final_name']=dpr_a['Relationship_Final_name'].astype(str)
<ipython-input-175-ec85dbbd700c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dpr_a['Relationship_Final_name']=dpr_a['Relationship_Final_name'].str.upper()
<ipython-input-175-ec85dbbd700c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dpr_a['Month']=dpr_a['Month'].astype(str)
<ipython-input-175-ec85dbbd700c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dpr_a['Premium']=dpr_a['Premium'].astype(float)

In [176]:
dpr_a=dpr_a.groupby(['Relationship_Final_name','Month']).sum()
dpr_a=dpr_a.reset_index(level=['Relationship_Final_name','Month'])
print(dpr_a.shape)
dpr_a.head(1)

(11488, 3)

  Relationship_Final_name Month   Premium
0         3 S AUTOMOTIVES   APR  0.302998

In [177]:
dpr_a['Average'] = dpr_a.groupby(['Relationship_Final_name','Month'])['Premium'].transform('mean')
dpr_a['Rank'] = dpr_a['Average'].rank(method='dense', ascending=False)
dpr_a['Rank']=dpr_a['Rank'].astype(int)
dpr_a=dpr_a.sort_values(by='Rank', ascending=True)
dpr_a['Premium']=dpr_a['Premium'].round(5)
dpr_a['Average']=dpr_a['Average'].round(5)
dpr_a.head(1)

   Relationship_Final_name Month      Premium      Average  Rank
76                    ABCD   APR  50632.21773  50632.21773     1

In [178]:
dpr_a['Percentage']=(dpr_a['Average']/(dpr_a.Premium.sum()))*100
dpr_a['Percentage']=dpr_a['Percentage'].astype(float)
dpr_a['Percentage']=dpr_a['Percentage'].round(5)
dpr_a.head(1)

   Relationship_Final_name Month      Premium      Average  Rank  Percentage
76                    ABCD   APR  50632.21773  50632.21773     1    62.78665

In [179]:
dpr_a=dpr_a.reset_index()
dpr_a=dpr_a.drop(columns=['index'])
dpr_a.head(1)

  Relationship_Final_name Month      Premium      Average  Rank  Percentage
0                    ABCD   APR  50632.21773  50632.21773     1    62.78665

In [180]:
dpr_a['sum'] = dpr_a['Percentage'].shift(0).cumsum().fillna(dpr_a['Percentage'].iat[0])
dpr_a['sum_1'] = dpr_a['sum']
dpr_a['sum_1'] = dpr_a['sum_1'].astype(int)
dpr_a.head(3)

,Relationship_Final_name,Month,Premium,Average,Rank,Percentage,sum,sum_1
0,ABCD,APR,50632.21773,50632.21773,1,62.78665,62.78665,62
1,YES BANK,APR,1419.59434,1419.59434,2,1.76037,64.54702,64
2,INVICTUS INSURANCE BROKING SERVICES,APR,508.63995,508.63995,3,0.63074,65.17776,65

In [181]:
dpr_a['bucket']=0
dpr_a.loc[dpr_a.sum_1 <= 25,'bucket'] = '0-25'
dpr_a.loc[(dpr_a.sum_1 > 25)&(dpr_a.sum_1 <= 50),'bucket'] = '26-50'
dpr_a.loc[(dpr_a.sum_1 > 50)&(dpr_a.sum_1 <= 75),'bucket'] = '51-75'
dpr_a.loc[(dpr_a.sum_1 > 75),'bucket'] = '76-100'
dpr_a.head(3)

,Relationship_Final_name,Month,Premium,Average,Rank,Percentage,sum,sum_1,bucket
0,ABCD,APR,50632.21773,50632.21773,1,62.78665,62.78665,62,51-75
1,YES BANK,APR,1419.59434,1419.59434,2,1.76037,64.54702,64,51-75
2,INVICTUS INSURANCE BROKING SERVICES,APR,508.63995,508.63995,3,0.63074,65.17776,65,51-75

In [182]:
dpr_a=dpr_a.rename(columns={'Premium':'Premium_groupby'})
print(dpr_a.shape)
dpr_a.head(1)

(11488, 9)

,Relationship_Final_name,Month,Premium_groupby,Average,Rank,Percentage,sum,sum_1,bucket
0,ABCD,APR,50632.21773,50632.21773,1,62.78665,62.78665,62,51-75

In [183]:
#MERGE
dpr9['Relationship_Final_name']=dpr9['Relationship_Final_name'].astype(str)
dpr9['Relationship_Final_name']=dpr9['Relationship_Final_name'].str.upper()
print(dpr9.shape)
dpr9.head(1)

(80585, 71)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Merged Name,Relationship_Final_code,Relationship_Final_name,Final_Code
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN,12A20064,G SUGANYA,10003277

In [184]:
dpr10=pd.merge(dpr9,dpr_a,on=(['Month','Relationship_Final_name']),how='left')
print(dpr10.shape)
dpr10.head(1)

(80585, 78)

,Zone,Issuing Region,Branch Name,Branch Code,Group Class,Agent Name,Agent Code,SM Code,SM Name,IMD Code,IMD Name,System,Actual Biz Type,Year,Product Category,Month,LOB Flag,Product SubCategory,Relationship Name,EXT_new_business_type,EXT_subchannel,EXT_relationship,EXT_markettype,RelationshipName_PR,Policy Count,Premium,SM_flag,Final_Branch_Code,SM_Code,DOJ,DOL_1,empstatus,SubChannel,Status,Role,SubChannel_Rev,SM_F,BM,CBM,RH,ZH,NM,VH_1,VH,SSM_R,BM_R,CBM_R,RH_R,ZH_R,NM_R,VH-1_R,VH_R,Repo-HRIS,ReportingCode,Class,GWP-Motor,GWP-Health,GWP-Commercial,GMC+GPA,LT_Flag,BM_F,CBM_F,RH_F,ZH_F,NM_F,VH_1_F,VH_F,Merged Name,Relationship_Final_code,Relationship_Final_name,Final_Code,Premium_groupby,Average,Rank,Percentage,sum,sum_1,bucket
0,CORPORATE ZONE,CORPORATE REGION,CORPORATE OFFICE,9201,ALL HEALTH,G SUGANYA,12A20064,99999998,NO SALES MANAGER,856909,I CARE SOLUTION,ICM,RENEWAL,2021-2022,HEALTH - INDIVIDUAL,APR,OTHERS,HEALTH GAIN,abcd,abcd,HEALTH AGENCY - TIED,nan,LARGE MARKET,abcd,1.0,0.18809,DIRECT,9201,99999998,abcd,1900-01-01,INACTIVE,ABCD,ABCD,ABCD,HEALTH AGENCY - TIED,99999999,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,abcd,GWP-Health,0.0,0.18809,0.0,0.0,No,abcd,abcd,abcd,abcd,10003277.0,70275004.0,70254315.0,NaN,12A20064,G SUGANYA,10003277,3.13604,3.13604,1329,0.00389,94.49457,94,76-100

In [185]:
df1.to_excel('OUTPUTS/Actual_code_apr.xlsx',index=False)
dpr10.to_excel('OUTPUTS/Actual_all_apr.xlsx',index=False)

# end